services:
  # MongoDB service
  mongo_db:
    container_name: core_db
    image: mongo@sha256:3b120f4dd854327f26ec51511e109be61f8f21329a53efa3646aa9212b8266d3 #7.0.14-rc0
    restart: always
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    volumes:
      - mongo_db:/data/db

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq@sha256:611107e29cce05c2acd968325d5dcbde7e2fee404970f1ead75fdb22be2821b3 #3.13.6-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "256M"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Node Access Cotrol service
  access_control:
    image: ghcr.io/abi-deployment-thesis/access-control@sha256:ae3d2081f3cecf0eb9d5a5082e1b8fe1045b89946bfdad07a30e6d502c9f1ccb #v1.0.1
    ports:
      - 3001:3001
    environment:
      HTTP_PORT: 3001
      MONGO_DB_URL: mongodb://core_db:27017/AccessControl?retryWrites=true&w=majority
      BCRYPT_SALT: 10
      JWT_SESSION_PASS: password
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
    depends_on:
      - mongo_db

  # Node Model Management service
  model_management:
    image: ghcr.io/abi-deployment-thesis/model-management@sha256:208523b1d5d2f4f42bf0415ca8f1fb42962d638506b03c78eb11db717d10eddf #v1.1.0
    ports:
      - 3002:3002
    environment:
      HTTP_PORT: 3002
      GRPC_PORT: 50052
      MONGO_DB_URL: mongodb://core_db:27017/ModelManagement?retryWrites=true&w=majority
      JWT_SESSION_PASS: password
      STORAGE_URL: /uploads
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
    depends_on:
      - mongo_db
    volumes:
      - ./uploads:/uploads

  # Node Model Runner service
  model_runner:
    image: ghcr.io/abi-deployment-thesis/model-runner@sha256:e18c76043939437b05ce4c8a915a0c9941f9cd3a7f1180a1be1d0c18f8750e97 #v1.1.0
    ports:
      - 3003:3003
    environment:
      HTTP_PORT: 3003
      GRPC_PORT: 50053
      GRPC_MODEL_MGMT_HOST: model_management:50052
      HTTP_MODEL_MGMT_HOST: model_management:3002
      GRPC_STABLE: "false"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DOCKER_ENGINE_QUEUE: docker_queue
      MONGO_DB_URL: mongodb://core_db:27017/ModelRunner?retryWrites=true&w=majority
      JWT_SESSION_PASS: password
      STORAGE_URL: /uploads
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
    depends_on:
      - mongo_db
    volumes:
      - ./uploads:/uploads

  # Python Docker Engine service
  docker_engine:
    image: ghcr.io/abi-deployment-thesis/docker-engine@sha256:88fb9e465fa61a65a7b4b0c76eaf4b4225bb437bf427a31e6bc9abd5e255c1b7 #v1.1.0
    environment:
      GRPC_MODEL_RUNNER_HOST: model_runner:50053
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: docker_queue
      DOCKER_HOST: tcp://host.docker.internal:2375
      DOCKER_TAG: docker-engine
      CONTAINER_PREFIX: run_
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./uploads:/uploads

  # Node ABI Deployment Webapp service
  # Note: This is for testing purposes only
  abi_deployment_webapp:
    image: ghcr.io/abi-deployment-thesis/abi-deployment-webapp@sha256:5094fba12b48015cadbe207817ce3851cffcea85b397edcb09f4cfdd9907c624 #v1.1.1
    ports:
      - 8080:80
    environment:
      MY_APP_ACCESS_CONTROL_BASE_URL: http://localhost:3001
      MY_APP_MODEL_MANAGEMENT_BASE_URL: http://localhost:3002
      MY_APP_MODEL_RUNNER_BASE_URL: http://localhost:3003
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
    depends_on:
      - access_control
      - model_management
      - model_runner

volumes:
  mongo_db: {}
  rabbitmq_data: