name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 #v2.0.8
        with:
          prerelease: ${{ contains(github.ref, '-alpha') }}
          generate_release_notes: true
          token: ${{ secrets.ACTION_TOKEN }}